import { Product, MenProductCategory, WomenProductCategory } from './types';

export const SHOP_NAME = 'Bhogendra Jewellers';
export const CONTACT_PHONE = '9931749410';
export const WHATSAPP_NUMBER = `91${CONTACT_PHONE}`;
export const SHOP_ADDRESS = 'Near Hanuman Temple Pali, Darbhanga, Bihar 847427, India';

export const ABOUT_US_TEXT = "Established in 1990, Bhogendra Jewellers has been a hallmark of trust, purity, and exquisite craftsmanship for over three decades. As a cherished family-owned business, we have dedicated ourselves to creating timeless pieces that are not just accessories, but heirlooms passed down through generations. Our passion lies in blending traditional artistry with contemporary designs, ensuring every piece of jewelry tells a unique story. We believe in building lasting relationships with our customers, founded on the promise of quality and a commitment to celebrating life's most precious moments with you.";

export const getWhatsAppMessage = (productName: string): string => {
  return `Hello ${SHOP_NAME}, I'm interested in the "${productName}". Can you please provide more details?`;
};

export const getCartWhatsAppMessage = (products: Product[]): string => {
  const productList = products.map(p => `- ${p.name} (${p.category})\nImage: ${p.imageUrl}`).join('\n\n');
  return `Hello ${SHOP_NAME}, I'm interested in the following items:\n\n${productList}\n\nCan you please provide more details?`;
};

export const WOMENS_CATEGORIES: WomenProductCategory[] = ['Rings', 'Necklaces', 'Bangles', 'Earrings', 'Nosepins', 'Mangalsutra', 'Maang Tikka'];
export const MENS_CATEGORIES: MenProductCategory[] = ['Chains', 'Rings', 'Bracelets'];

export const PRODUCTS: Product[] = [
  // Rings (Women)
  { id: 1, name: 'Resplendent Floral Majesty Finger Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw2bd7164b/images/hi-res/51W2BHFIWAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 2, name: 'Marvellous Meshed-Blossoms Finger Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwdb4edfec/images/hi-res/51W2BHFIUAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 3, name: 'Resplendent Floral Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwf118a467/images/hi-res/51W2BHFIYAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 4, name: 'Breeze Bloom Gold Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwd2f041fe/images/hi-res/51M5B1FGYAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 21, name: 'Twist Shine Gold Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw468cd430/images/hi-res/51D5B2FSWAACZ_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 22, name: 'Floral Charm Gold Finger Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw3bc46414/images/hi-res/51D5B2FBFAACZ_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 31, name: 'Petal Lace Gold Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwd0597bad/images/hi-res/51D5B2FDHAACZ_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 32, name: 'Dainty Elegant Ring', category: 'Rings', imageUrl: 'http://tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw13127b47/images/hi-res/51D2D2FKKAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 53, name: 'Grace Wrap Gold Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw7c736bed/images/hi-res/51M4C1FFFAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 54, name: 'Vintage Gold Band', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwa9dc1b42/images/hi-res/51M5B1FCAAA00_1.jpg', gender: 'Women' },
  { id: 55, name: 'Refreshing 22 Karat Yellow Gold Leaf Finger Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwe166ceb8/images/hi-res/512220FEQAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 56, name: 'Glorious 22 Karat Yellow Gold Floral Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw908fe0fa/images/hi-res/511920FCMAA00.jpg?sw=640&sh=640', gender: 'Women' },

  // Necklaces (Women)
  { id: 5, name: 'Floral Drop Gold Necklace', category: 'Necklaces', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwc7c0ff54/images/hi-res/51W5B1NRFAAP1_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 6, name: 'Crowned Curve Gold Necklace', category: 'Necklaces', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwcfda337c/images/hi-res/51W4PINMNAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 7, name: 'Crest Sparkle Gold Necklace', category: 'Necklaces', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwa89205d2/images/hi-res/51W4PINMVAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 8, name: 'Gilded Garland Gold Necklace', category: 'Necklaces', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw30154002/images/hi-res/51W4PINMTAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 23, name: 'Striking Gold Necklace for the Kannadiga Bride', category: 'Necklaces', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw3198a16b/images/hi-res/512113NSSAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 24, name: 'Gentle Flight Diamond Necklace', category: 'Necklaces', imageUrl: 'https://www.tanishq.co.in/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dweab844bd/images/hi-res/50D3FFNAFAA02_1.jpg', gender: 'Women' },
  { id: 33, name: 'Ornate Bloom Gold Necklace', category: 'Necklaces', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwe972536f/images/hi-res/51D5M2NSSAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 34, name: 'Floral Radiance Gold Necklace', category: 'Necklaces', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw532c5369/images/hi-res/51D5M2NSZAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 57, name: 'Glam Twist Gold Necklace', category: 'Necklaces', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw621cce3d/images/hi-res/51M4I1NJWAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 58, name: 'Sparkling Reflections Solitaire Necklace', category: 'Necklaces', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw7963a951/images/hi-res/NOD1NAZ.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 59, name: 'Gentle Flight Diamond Necklace', category: 'Necklaces', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dweab844bd/images/hi-res/50D3FFNAFAA02_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 60, name: 'Delicate Diamond Necklace', category: 'Necklaces', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwe142d673/images/hi-res/512762NTQAA28_1.jpg?sw=640&sh=640', gender: 'Women' },

  // Bangles (Women)
  { id: 9, name: 'Brilliant Gold Bangle', category: 'Bangles', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwf540018f/images/hi-res/512411VQN2A00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 10, name: 'Joyful Knots Gold Bangle', category: 'Bangles', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw891d5cbb/images/hi-res/51K5B1VRW1A00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 11, name: 'Antique Aura Gold Bangles', category: 'Bangles', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw5cc321a6/images/hi-res/51W5D2VAM2A00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 12, name: 'Radiant Royale Diamond Bangles', category: 'Bangles', imageUrl: 'https://www.tanishq.co.in/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwc17bb0f9/images/hi-res/50W5PLVFO2A28_1.jpg', gender: 'Women' },
  { id: 25, name: 'Royal Grace Gold Bangles', category: 'Bangles', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw2300b5d5/images/hi-res/51W5DXVAF2A00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 26, name: 'Crowned Grace Gold Bangles', category: 'Bangles', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw242a3ca1/images/hi-res/51W5D2VAF2A00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 35, name: 'Artistic Grace Gold Bangles', category: 'Bangles', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw8d7ed8ed/images/hi-res/51W5C2VUG2A00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 36, name: 'Majestic Arcadia Gold Bangles', category: 'Bangles', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw4527f510/images/hi-res/51W5V2VIM2A00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 61, name: 'Enamel Medallion Gold Bangles', category: 'Bangles', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw986d2847/images/hi-res/51W5C2VJF2A00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 62, name: 'Majestic Floral Gold Bangle', category: 'Bangles', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw90424241/images/hi-res/51W5CLVAN1A00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 63, name: 'Artistic Leaf Gold Bangles', category: 'Bangles', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwf59c8441/images/hi-res/51W5C2VUH2A00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 64, name: 'Enamel Flourish Gold Bangles', category: 'Bangles', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw2042e961/images/hi-res/51W5C2VUD2A00_1.jpg?sw=640&sh=640', gender: 'Women' },

  // Earrings (Women)
  { id: 13, name: 'Little Bells Gold Jhumka Earrings', category: 'Earrings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwfd756f43/images/hi-res/516060JFDAGA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 14, name: 'Little Joy Gold Jhumka Earrings', category: 'Earrings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw3082a2b4/images/hi-res/516060JEYAGA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 15, name: 'Blooming 22 Karat Yellow Gold Beaded Floral Drop Earrings', category: 'Earrings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwc71f171d/images/hi-res/512220DAUAJA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 16, name: 'Floral Dome Gold Jhumka Earrings', category: 'Earrings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw0b3d3e4b/images/hi-res/51D5M2JAZABA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 27, name: 'Palace Charm Gold Jhumka Earrings', category: 'Earrings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw01d7f324/images/hi-res/51D5C1JGRABA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 28, name: 'Royal Teardrop Gold Jhumka Earrings', category: 'Earrings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwfa7690c1/images/hi-res/51D5C1JFOABA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 37, name: 'Jharlanthaner Jhalok Gold Jhumka Earrings', category: 'Earrings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwf00b27a7/images/hi-res/51W5DPJBFABA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 38, name: 'Jharbaati Prabha Gold Jhumka Earrings', category: 'Earrings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw5b974b38/images/hi-res/51W5DPJBHABA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 65, name: 'Alpona Pushpa Gold Pasha Earrings', category: 'Earrings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwe234e87d/images/hi-res/51W5DPSADABA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 66, name: 'Kolka Filigree Gold Pasha Earrings', category: 'Earrings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwf42021bf/images/hi-res/51W5DPSAJABA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 67, name: 'Shola Bloom Gold Pasha Earrings', category: 'Earrings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwb3fd1d5b/images/hi-res/51W5DPSAKABA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 68, name: 'Shola Grandeur Gold Pasha Earrings', category: 'Earrings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw0230976b/images/hi-res/51W5DPSAEABA00_1.jpg?sw=640&sh=640', gender: 'Women' },

  // Nosepins (Women)
  { id: 17, name: 'Enchanting Gold Nath for the Bihari Bride', category: 'Nosepins', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw73dcdaba/images/hi-res/513017OCOAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 18, name: 'Stunning Gold Nath', category: 'Nosepins', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw7501963b/images/hi-res/513017OCPAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 19, name: 'Traditional Gold Nath', category: 'Nosepins', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwa711ba1d/images/hi-res/513018OSPAABP3_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 20, name: 'Superlative Yellow Gold Floral Filigree Nath', category: 'Nosepins', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw983e17cb/images/hi-res/512016OUJAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 29, name: 'Marvellous Gold Nath for the Punjabi Bride', category: 'Nosepins', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw5fec2a79/images/hi-res/51AC41OACAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 30, name: 'Brilliant Yellow Gold Floral Nath', category: 'Nosepins', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwbbefbe83/images/hi-res/511207OBPAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 39, name: 'Opulent Gold Nath for the Contemporary Bride', category: 'Nosepins', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw9d6cdbc6/images/hi-res/512218ONAAARP1_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 40, name: 'Rose Inspired Gold and Diamond Nose Pin', category: 'Nosepins', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwa381434a/images/hi-res/502614OCVAAA04_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 69, name: 'Dew Aura Diamond Nose Pin', category: 'Nosepins', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwa1352e1a/images/hi-res/50D5H1OCLAPA02_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 70, name: 'Floral Elegance Gold Nose Pin', category: 'Nosepins', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw4c553e7b/images/hi-res/51D4I1OGPAPA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 71, name: 'Beaded Teardrop Gold', category: 'Nosepins', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw63c9d81f/images/hi-res/51D4I1OHBAPA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 72, name: 'Exquisite Leaf Gold', category: 'Nosepins', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw8addfa26/images/hi-res/51D4B1OJYAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 74, name: 'Leaf Whisper Gold Nose Pin', category: 'Nosepins', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw6d7e499b/images/hi-res/51D4B1OJPAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },

  // Mangalsutra (Women)
  { id: 86, name: 'Timeless Bond Gold Mangalsutra', category: 'Mangalsutra', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw3739fe30/images/hi-res/50D5C1YATAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 87, name: 'Auspicious Harmony Gold Mangalsutra', category: 'Mangalsutra', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwa16a440d/images/hi-res/50D5C1YAVAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 88, name: 'Celestial Grace Gold Mangalsutra', category: 'Mangalsutra', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwcec8a6a2/images/hi-res/50D5C1YAUAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 89, name: 'Arch Gleam Gold Mangalsutra', category: 'Mangalsutra', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw1f484fe0/images/hi-res/51D5B2YSAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 94, name: 'Traditional Elegant Mangalsutra', category: 'Mangalsutra', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwa7a77f05/images/hi-res/511138YFJAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 95, name: 'Ornate Carved Mangalsutra', category: 'Mangalsutra', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw9c724c79/images/hi-res/512M19YBJAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 96, name: 'Spellbinding Gold Mangalsutra', category: 'Mangalsutra', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw4bdbc9d8/images/hi-res/51D3D2YLKAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 97, name: 'Gold Bead Mangalsutra', category: 'Mangalsutra', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwaa56c16a/images/hi-res/511250YHTAA00_1.jpg?sw=640&sh=640', gender: 'Women' },

  // Maang Tikka (Women)
  { id: 90, name: 'Lotus Crest Gold Maang Tikka', category: 'Maang Tikka', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwb3edccb7/images/hi-res/50W5V2KCGAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 91, name: 'Ethnic Gold Maang Tikka', category: 'Maang Tikka', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwfd29f026/images/hi-res/513020KHPAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 92, name: 'Blossom Crest Gold Maang Tikka', category: 'Maang Tikka', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwcde90e45/images/hi-res/50W5V2KBNAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 93, name: 'Regal Chandeliers Gold Maang Tikka', category: 'Maang Tikka', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw65cd01c1/images/hi-res/50W5V2KBOAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 98, name: 'Regal Ornate Gold Maang Tikka', category: 'Maang Tikka', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw0c4b51bd/images/hi-res/50W5V2KGFAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 99, name: 'Serene Grace Gold Maang Tikka', category: 'Maang Tikka', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw244eb853/images/hi-res/51W4RIKDQAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 100, name: 'Carved Round Gold Maang Tikka', category: 'Maang Tikka', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwb370bb1e/images/hi-res/512520KGLAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },
  { id: 101, name: 'Classical Beauty Maang Tikka', category: 'Maang Tikka', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw6038ecb0/images/hi-res/511207KCRAAA00_1.jpg?sw=640&sh=640', gender: 'Women' },

  // MEN'S COLLECTION
  // Chains (Men)
  { id: 41, name: 'Majestic Gold Chain', category: 'Chains', imageUrl: 'https://www.tanishq.co.in/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw254d7fd0/images/hi-res/511038CUAAA00_2.jpg', gender: 'Men' },
  { id: 42, name: 'Enticing Gold Chain', category: 'Chains', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwf702f8ad/images/hi-res/510783CSAAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 43, name: 'Two Toned Link Gold Chain', category: 'Chains', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw15dd3f2e/images/hi-res/513220CMXAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 44, name: 'Bold Pattern Gold Chain', category: 'Chains', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dweacea9bc/images/hi-res/51G5C1CBJAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 73, name: 'Woven Link Gold Chain', category: 'Chains', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw3e53a409/images/hi-res/50G5C1CBWLA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 75, name: 'Rugged Rhythm Gold Chain', category: 'Chains', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwb76f24f7/images/hi-res/50G5B1CBSLA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 76, name: 'Rope Twist Gold Chain', category: 'Chains', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw65f976f9/images/hi-res/50G5C1CBVAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 77, name: 'Rope Pattern Gold Chain', category: 'Chains', imageUrl: 'https://www.tanishq.co.in/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwdc69f4b3/images/hi-res/51F1D1CPXAB00_1.jpg', gender: 'Men' },

  // Rings (Men)
  { id: 45, name: 'Flow Edge Gold Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw59d070e6/images/hi-res/51G5B1FGGAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 46, name: 'Radiant Legacy Gold Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw731f3228/images/hi-res/51G5B1FGHAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 47, name: 'Solar Forge Gold Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw450e2bc2/images/hi-res/51G5B1FDKAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 48, name: 'Anchor Spirit Gold Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw1f93dd97/images/hi-res/51G5AMFECAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 78, name: 'Royal 22 Karat Yellow Gold Lord Ganesha Finger Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw64b52aa8/images/hi-res/512814FNAAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 79, name: 'Sleek Geometric Gold Finger Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw8f3e5147/images/hi-res/512218FCIAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 80, name: 'Charming Twisted Motif Gold Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw9b64f4e3/images/hi-res/511003FEKAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 81, name: 'Ribbed 22 Karat Gold Finger Ring', category: 'Rings', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw27f3c20a/images/hi-res/511003FEGAA00_1.jpg?sw=640&sh=640', gender: 'Men' },

  // Bracelets (Men)
  { id: 49, name: 'Woven Crest Gold Bracelet', category: 'Bracelets', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw69d073bb/images/hi-res/51G5B1BALAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 50, name: 'Timeless Classic Gold Bracelet', category: 'Bracelets', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwaf3829e5/images/hi-res/51G4C1BDOAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 51, name: 'Grid Link Gold Bracelet', category: 'Bracelets', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw364b8a44/images/hi-res/51G5C1BEHAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 52, name: 'Regal Charm Gold Bracelet', category: 'Bracelets', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw5c63d42c/images/hi-res/51G5C1BDVAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 82, name: 'Infinity Link Gold Bracelet', category: 'Bracelets', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw3d3c9ea8/images/hi-res/51G5C1BEJAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 83, name: 'Splendid Gold Bracelet', category: 'Bracelets', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwa047a861/images/hi-res/511003BAZAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 84, name: 'Classy Bracelet', category: 'Bracelets', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwa4a05a58/images/hi-res/511159BTAAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
  { id: 85, name: 'Geometric Design Gold Bracelet', category: 'Bracelets', imageUrl: 'https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw476cb7b6/images/hi-res/51G2PTBHTAA00_1.jpg?sw=640&sh=640', gender: 'Men' },
];